# From: https://danielgroves.net/notebook/2014/05/development-environments/
# Adapted for ubuntu since Travis-CI operates under ubuntu.
- name: Install packages
  become: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      # Python Dev
      - python-dev
      - python-setuptools
      - python-virtualenv

- name: Install virtualenvwrapper
  pip: name=virtualenvwrapper

- name: Add vagrant user to docker group
  user: name=vagrant groups=docker

- name: Add virtualenv info to vagrant user profile
  lineinfile: dest=/home/vagrant/.profile line="export WORKON_HOME=$HOME/Virtualenvs\nif [ -f /usr/local/bin/virtualenvwrapper.sh ]; then\n source /usr/local/bin/virtualenvwrapper.sh\nfi"

